import ClientLayout from '@/components/client/ClientLayout'
import FormProvider from '@/contexts/formContext'
import { ThemeProvider } from '@/contexts/themeContext'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Desbrave o esporte',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <FormProvider>
      <ThemeProvider>
        <ClientLayout>{children}</ClientLayout>
      </ThemeProvider>
    </FormProvider>
  )
}
